### ISSUE TITLE
ro.pippo.core.PippoRuntimeException: Method 'ro.pippo.demo.controller.ContactsController::get' parameter 0 does not specify a name!

### ISSUE THREAD

**Issue by billysAnna** [decebals/pippo-demo#15]
I start the ControllerDemo, type 'http://127.0.0.1:8338/contacts/api/1' in browser,  but got an exception.
I want to use restful style controller with ro.pippo.demo.controller.ContactsController#get.
Branch I use is master.
Statcktrace follows:
ro.pippo.core.PippoRuntimeException: Method 'ro.pippo.demo.controller.ContactsController::get' parameter 0 does not specify a name!
	at ro.pippo.controller.extractor.ParamExtractor.getParameterName(ParamExtractor.java:69)
	at ro.pippo.controller.extractor.ParamExtractor.extract(ParamExtractor.java:44)
	at ro.pippo.controller.ControllerRouteHandler.prepareMethodParameters(ControllerRouteHandler.java:388)
	at ro.pippo.controller.ControllerRouteHandler.handle(ControllerRouteHandler.java:120)
	at ro.pippo.core.route.DefaultRouteContext.handleRoute(DefaultRouteContext.java:394)
	at ro.pippo.core.route.DefaultRouteContext.next(DefaultRouteContext.java:276)
	at ro.pippo.demo.controller.ControllerApplication.lambda$onInit$0(ControllerApplication.java:45)
	at ro.pippo.core.route.DefaultRouteContext.handleRoute(DefaultRouteContext.java:394)
	at ro.pippo.core.route.DefaultRouteContext.next(DefaultRouteContext.java:276)
	at ro.pippo.core.route.RouteDispatcher.onRouteDispatch(RouteDispatcher.java:153)
	at ro.pippo.core.route.RouteDispatcher.dispatch(RouteDispatcher.java:101)
	at ro.pippo.core.PippoFilter.processRequest(PippoFilter.java:179)
	at ro.pippo.core.websocket.AbstractWebSocketFilter.processRequest(AbstractWebSocketFilter.java:37)
	at ro.pippo.core.PippoFilter.doFilter(PippoFilter.java:153)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1160)
	at ro.pippo.jetty.JettyServer$PippoHandler.doHandle(JettyServer.java:255)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1092)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:518)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:244)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:246)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:156)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)

**Comment by decebals** [comment]
https://github.com/decebals/pippo/pull/341#issuecomment-274041991

**Comment by decebals** [comment]
You try to run `ControllerDemo` from command line or from IDE (Idea, Eclipse, Netbeans)?

**Comment by billysAnna** [comment]
I use idea, with this pom segment
![aaaaaaaaaaaaaaaaaaaaaaaaaa](https://user-images.githubusercontent.com/12570910/26972547-e3d818a6-4d44-11e7-911b-ec6c899849b9.png)

**Comment by decebals** [comment]
This is my Run Configuration from IDEA for ControllerDemo:

![image](https://user-images.githubusercontent.com/1248311/26972676-73a06e9a-4d1b-11e7-894f-ab6184acffe3.png)

**Comment by billysAnna** [comment]
I run `mvn clean install` in cmd windows, and it works, but I use `mvn clean package` before. Is this the reason?

**Comment by decebals** [comment]
And my project settings:

![image](https://user-images.githubusercontent.com/1248311/26972851-2dae3fd8-4d1c-11e7-8921-2fa2d54bab06.png)

**Comment by decebals** [comment]
> I run mvn clean install in cmd windows, and it works, but I use mvn clean package before. Is this the reason?

I don't think. Both (install and package) call compile in the end.

**Comment by billysAnna** [comment]
oh no, exception occurs again.
This is starting info without text '-parameters',  abnormal?
"C:\Program Files\Java\jdk1.8.0_121\bin\java" -Didea.launcher.port=7538 "-Didea.launcher.bin.path=C:\Program Files (x86)\JetBrains\IntelliJ IDEA 14.0.5\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Java\jdk1.8.0_121\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\rt.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\zipfs.jar;C:\code-git\git-other\pippo-demo\pippo-demo-controller\target\classes;C:\code-git\git-other\pippo-demo\pippo-demo-common\target\classes;D:\maven-repo\ro\pippo\pippo-core\1.4.0\pippo-core-1.4.0.jar;D:\maven-repo\org\slf4j\slf4j-api\1.7.7\slf4j-api-1.7.7.jar;D:\maven-repo\ro\pippo\pippo-controller\1.4.0\pippo-controller-1.4.0.jar;D:\maven-repo\ro\pippo\pippo-freemarker\1.4.0\pippo-freemarker-1.4.0.jar;D:\maven-repo\org\freemarker\freemarker\2.3.23\freemarker-2.3.23.jar;D:\maven-repo\org\ocpsoft\prettytime\prettytime\3.2.5.Final\prettytime-3.2.5.Final.jar;D:\maven-repo\ro\pippo\pippo-fastjson\1.4.0\pippo-fastjson-1.4.0.jar;D:\maven-repo\com\alibaba\fastjson\1.2.8\fastjson-1.2.8.jar;D:\maven-repo\ro\pippo\pippo-metrics\1.4.0\pippo-metrics-1.4.0.jar;D:\maven-repo\io\dropwizard\metrics\metrics-core\3.1.1\metrics-core-3.1.1.jar;D:\maven-repo\io\dropwizard\metrics\metrics-jvm\3.1.1\metrics-jvm-3.1.1.jar;D:\maven-repo\org\webjars\bootstrap\3.3.1\bootstrap-3.3.1.jar;D:\maven-repo\org\webjars\jquery\1.11.1\jquery-1.11.1.jar;D:\maven-repo\org\webjars\font-awesome\4.2.0\font-awesome-4.2.0.jar;D:\maven-repo\org\slf4j\slf4j-simple\1.7.7\slf4j-simple-1.7.7.jar;D:\maven-repo\ro\pippo\pippo-jetty\1.4.0\pippo-jetty-1.4.0.jar;D:\maven-repo\org\eclipse\jetty\jetty-server\9.3.8.v20160314\jetty-server-9.3.8.v20160314.jar;D:\maven-repo\javax\servlet\javax.servlet-api\3.1.0\javax.servlet-api-3.1.0.jar;D:\maven-repo\org\eclipse\jetty\jetty-http\9.3.8.v20160314\jetty-http-9.3.8.v20160314.jar;D:\maven-repo\org\eclipse\jetty\jetty-util\9.3.8.v20160314\jetty-util-9.3.8.v20160314.jar;D:\maven-repo\org\eclipse\jetty\jetty-io\9.3.8.v20160314\jetty-io-9.3.8.v20160314.jar;D:\maven-repo\org\eclipse\jetty\jetty-annotations\9.3.8.v20160314\jetty-annotations-9.3.8.v20160314.jar;D:\maven-repo\org\eclipse\jetty\jetty-plus\9.3.8.v20160314\jetty-plus-9.3.8.v20160314.jar;D:\maven-repo\org\eclipse\jetty\jetty-jndi\9.3.8.v20160314\jetty-jndi-9.3.8.v20160314.jar;D:\maven-repo\org\eclipse\jetty\jetty-webapp\9.3.8.v20160314\jetty-webapp-9.3.8.v20160314.jar;D:\maven-repo\org\eclipse\jetty\jetty-xml\9.3.8.v20160314\jetty-xml-9.3.8.v20160314.jar;D:\maven-repo\javax\annotation\javax.annotation-api\1.2\javax.annotation-api-1.2.jar;D:\maven-repo\org\ow2\asm\asm\5.0.1\asm-5.0.1.jar;D:\maven-repo\org\ow2\asm\asm-commons\5.0.1\asm-commons-5.0.1.jar;D:\maven-repo\org\ow2\asm\asm-tree\5.0.1\asm-tree-5.0.1.jar;D:\maven-repo\org\eclipse\jetty\websocket\websocket-server\9.3.8.v20160314\websocket-server-9.3.8.v20160314.jar;D:\maven-repo\org\eclipse\jetty\websocket\websocket-common\9.3.8.v20160314\websocket-common-9.3.8.v20160314.jar;D:\maven-repo\org\eclipse\jetty\websocket\websocket-api\9.3.8.v20160314\websocket-api-9.3.8.v20160314.jar;D:\maven-repo\org\eclipse\jetty\websocket\websocket-client\9.3.8.v20160314\websocket-client-9.3.8.v20160314.jar;D:\maven-repo\org\eclipse\jetty\websocket\websocket-servlet\9.3.8.v20160314\websocket-servlet-9.3.8.v20160314.jar;D:\maven-repo\org\eclipse\jetty\jetty-servlet\9.3.8.v20160314\jetty-servlet-9.3.8.v20160314.jar;D:\maven-repo\org\eclipse\jetty\jetty-security\9.3.8.v20160314\jetty-security-9.3.8.v20160314.jar;D:\maven-repo\ro\pippo\pippo-jaxb\1.4.0\pippo-jaxb-1.4.0.jar;C:\Program Files (x86)\JetBrains\IntelliJ IDEA 14.0.5\lib\idea_rt.jar" com.intellij.rt.execution.application.AppMain ro.pippo.demo.controller.ControllerDemo

**Comment by decebals** [comment]
It's OK. Parameters `-parameters` is required only on compile.

**Comment by billysAnna** [comment]
changing to eclipse, the question still exists. `http://127.0.0.1:8338/contacts/uriFor/1` and `http://127.0.0.1:8338/contacts/api/1` give the same exception. 
[I am from china, having little resource of pippo.]

ro.pippo.core.PippoRuntimeException: Method 'ro.pippo.demo.controller.ContactsController::uriFor' parameter 0 does not specify a name!
	at ro.pippo.controller.extractor.ParamExtractor.getParameterName(ParamExtractor.java:69)
	at ro.pippo.controller.extractor.ParamExtractor.extract(ParamExtractor.java:44)
	at ro.pippo.controller.ControllerRouteHandler.prepareMethodParameters(ControllerRouteHandler.java:388)
	at ro.pippo.controller.ControllerRouteHandler.handle(ControllerRouteHandler.java:120)
	at ro.pippo.metrics.TimedRouteHandler.handle(TimedRouteHandler.java:43)
	at ro.pippo.core.route.DefaultRouteContext.handleRoute(DefaultRouteContext.java:394)
	at ro.pippo.core.route.DefaultRouteContext.next(DefaultRouteContext.java:276)
	at ro.pippo.demo.controller.ControllerApplication.lambda$onInit$0(ControllerApplication.java:45)
	at ro.pippo.core.route.DefaultRouteContext.handleRoute(DefaultRouteContext.java:394)
	at ro.pippo.core.route.DefaultRouteContext.next(DefaultRouteContext.java:276)
	at ro.pippo.core.route.RouteDispatcher.onRouteDispatch(RouteDispatcher.java:153)
	at ro.pippo.core.route.RouteDispatcher.dispatch(RouteDispatcher.java:101)
	at ro.pippo.core.PippoFilter.processRequest(PippoFilter.java:179)

**Comment by billysAnna** [comment]
i debug and find that method in ro.pippo.controller.MethodParameter

    public String getParameterName() {
        if (parameterName == null) {
            Parameter parameter = getParameter();
            **if (parameter.isNamePresent()) { // this expression is false, so the method returns null**
                parameterName = parameter.getName();
            }
        }

        return parameterName;
    }

so 
variable `name` in method ro.pippo.controller.extractor.ParamExtractor#getParameterName  is null, makes the exception.
    private String getParameterName(MethodParameter parameter, Param annotation) {
        String name = annotation.value();
        if (StringUtils.isNullOrEmpty(name)) {
            name = parameter.getParameterName();
        }

        if (name == null) {
            throw new PippoRuntimeException(
                "Method '{}' parameter {} does not specify a name!",
                LangUtils.toString(parameter.getMethod()), parameter.getParameterIndex());
        }

        return name;
    }

**Comment by billysAnna** [comment]
in eclipse, follow step `Window -> Preferences -> Java -> Compile -> Store information about method parameters (usable via reflection)` will works.

Thank you very much !

i cannot upload picture because of `Something went really wrong, and we can’t process that file. `.

**Comment by billysAnna** [comment]
in idea, follow step `File -> Setting -> Build,Execution,Deployment -> Compiler -> Java Compile `
add `-parameters` to `Additional command line parameter`

look picture :
![default](https://user-images.githubusercontent.com/12570910/26974746-5fe116aa-4d4f-11e7-82f1-bbea04f21dee.png)
![eclipse-jdk8-ok](https://user-images.githubusercontent.com/12570910/26974785-7e743ab6-4d4f-11e7-809d-20d1f36d1843.png)

**Comment by Nosredna333** [comment]
In Red Hat Developer Studio Version: 12.0.0.GA, I set this, clear Eclipse File Cache, rebuild all Aplication, and the error come again....

**Comment by Nosredna333** [comment]
I found error!
The sample came with method this way
        public void saveContact( /\*@Body\*/ Contact contact) {

The annotation needs are enabled. Just uncomment, set -parameters for javac and finally works!
